import type { Metadata } from "next";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { ServiceStructuredData } from "@/components/StructuredData";
import { ProductionAction, ProductionCard, ProductionClosing, ProductionContainer, ProductionKicker } from "@/components/ProductionPrimitives";
import { ReviewImageDirection } from "@/components/ReviewImageDirection";

export const metadata: Metadata = { title: "Online Workplace Wellbeing", description: "Human-led online workplace wellbeing for remote, hybrid and distributed teams.", alternates: { canonical: "/online-wellbeing" } };

export default function OnlineWellbeingPage() {
  return <>
    <ServiceStructuredData name="Online Workplace Wellbeing" description="Human-led online workplace wellbeing for remote, hybrid and distributed teams." path="/online-wellbeing" breadcrumbLabel="Online Wellbeing" />
    <Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Online Wellbeing" }]} />
    <section className="bg-[var(--cya-teal-dark)] py-16 text-white lg:py-20"><ProductionContainer><ProductionKicker light>Human-led continuity</ProductionKicker><h1 className="mt-5 max-w-4xl text-[clamp(2.8rem,5vw,4.5rem)] font-bold leading-[1.05] text-white">Keep useful wellbeing connected across hybrid work.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-white/85">Online Wellbeing extends the CYA relationship across locations and working patterns. It is a connected service—not a standalone platform proposition.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><ProductionAction href="#online-service" style="secondary">Explore Online Wellbeing</ProductionAction><ProductionAction href="/contact?interest=program" style="secondary">Plan a connected program</ProductionAction></div></ProductionContainer></section>
    <ReviewImageDirection id="IMAGE 08 · ONLINE AND HYBRID PARTICIPATION" job="Context" subject="A genuine CYA online or hybrid experience showing human facilitation and people joining from more than one workplace context." treatment="Contained 3:2 image or carefully composed two-frame field note. Keep screens readable only where permission allows." format="3:2 desktop · adaptable to 4:3 mobile" avoid="Generic laptop stock, artificial video-call grids, visible private information, or imagery that makes Online Wellbeing look like standalone software." candidate="/images/selected/cya-online-wellbeing-context.webp" />
    <section id="online-service" className="bg-[var(--cya-paper)] py-20 lg:py-24"><ProductionContainer><ProductionKicker>One relationship across locations</ProductionKicker><h2 className="mt-5 text-4xl font-bold lg:text-5xl">Digital access is part of the service rhythm.</h2><p className="mt-5 max-w-4xl text-lg text-[var(--cya-body)]">Online Wellbeing supports distributed teams through coordinated live experiences, useful resources and ongoing human curation.</p><div className="mt-10 grid gap-5 md:grid-cols-3"><ProductionCard title="Live online experiences" body="Human facilitation across locations with formats adapted for online participation." /><ProductionCard title="Useful resources between sessions" body="Short practices and expert material connected to the agreed workplace need." /><ProductionCard title="A visible Working Rhythm" body="A coherent cadence that can be reviewed and adapted with the organisation." /></div></ProductionContainer></section>
    <section className="bg-[var(--cya-teal-dark)] py-20 text-white lg:py-24"><ProductionContainer><ProductionKicker light>Wellbeing Studio by Corporate Yoga Australia</ProductionKicker><h2 className="mt-5 text-4xl font-bold text-white lg:text-5xl">Useful support between live moments.</h2><p className="mt-5 max-w-4xl text-lg leading-8 text-white/85">Wellbeing Studio can give participants a useful place to return to as part of a CYA service relationship, while planning, curation and support remain human-led.</p><div className="mt-10 grid gap-5 md:grid-cols-3"><ProductionCard title="Return" body="Short practices and useful resources remain available when people need them." /><ProductionCard title="Connect" body="Live and digital experiences can support one coherent workplace rhythm." /><ProductionCard title="Support" body="Access, curation, communication and review remain part of the CYA relationship." /></div></ProductionContainer></section>
    <ProductionClosing tone="teal" heading="Build continuity without losing the human relationship." body="Shape an online rhythm around access, relevance and organisational confidence." href="/contact?interest=online" action="Explore Online Wellbeing" />
  </>;
}
