import type { MediaAsset } from "@/lib/types";

/**
 * Curated photography selected from the provisional library. Every entry is
 * `evidence-required`: none of this library's publication consent is
 * documented (see Docs/CYA_Prototype_v1_Image_Audit.md and
 * CYA_Prototype_v1_Image_Mapping.md). The note is shown only in annotation mode.
 */
const PERMISSION_NOTE = "Provisional library image — publication consent not documented. Permission to confirm; replace after the future photo shoot.";

export const media = {
  homeHero: {
    src: "/images/selected/cya-home-hero-workplace-session.webp",
    width: 1080,
    height: 810,
    alt: "A diverse group of colleagues in a meeting room, seated with hands together in a shared moment of calm.",
    status: "evidence-required",
    note: PERMISSION_NOTE,
  },
  homeOneOff: {
    src: "/images/selected/cya-home-oneoff-desk-stretch.webp",
    width: 1600,
    height: 1200,
    alt: "Two colleagues pausing at a desk for a guided stretch.",
    status: "evidence-required",
    note: PERMISSION_NOTE,
  },
  workplaceWellbeingHero: {
    src: "/images/selected/cya-workplace-wellbeing-hero-warehouse-group.webp",
    width: 1354,
    height: 1016,
    alt: "A team doing a standing stretch together on the floor of a warehouse.",
    status: "evidence-required",
    note: PERMISSION_NOTE,
  },
  debbyTeacherPortrait: {
    src: "/images/selected/cya-people-debby-teacher-portrait.webp",
    width: 1600,
    height: 1200,
    alt: "Debby Lewis, seated and smiling, in a plant-filled studio space.",
    status: "approved",
    note: "Named subject — Debby Lewis, CYA founder. Approved for CYA's own site use.",
  },
  workplaceWellbeingLunchLearn: {
    src: "/images/selected/cya-workplace-wellbeing-lunch-learn-team.webp",
    width: 1080,
    height: 810,
    alt: "A small team stretching together in an office breakout space, including a colleague in high-visibility workwear.",
    status: "evidence-required",
    note: PERMISSION_NOTE,
  },
  movementHero: {
    src: "/images/selected/cya-movement-desk-stretch-office.webp",
    width: 1000,
    height: 750,
    alt: "A man in business attire stretching at his desk between meetings.",
    status: "evidence-required",
    note: PERMISSION_NOTE + " Higher-resolution source required for large placements.",
  },
  movementGroupIndustrial: {
    src: "/images/selected/cya-movement-group-industrial.webp",
    width: 1600,
    height: 1200,
    alt: "A group of men doing a standing stretch together in an industrial facility.",
    status: "evidence-required",
    note: PERMISSION_NOTE,
  },
  movementFacilitatorAdjustment: {
    src: "/images/selected/cya-movement-facilitator-adjustment.webp",
    width: 1600,
    height: 1200,
    alt: "A facilitator gently guiding a participant through a supported stretch.",
    status: "evidence-required",
    note: PERMISSION_NOTE,
  },
  conferencesHero: {
    src: "/images/selected/cya-conferences-hero-facilitator-led-group.webp",
    width: 960,
    height: 720,
    alt: "A facilitator leading a group relaxation session in a bright indoor space.",
    status: "evidence-required",
    note: "Named facilitator (Debby Lewis) — group members' consent not documented. " + PERMISSION_NOTE,
  },
  conferencesStudioAccess: {
    src: "/images/selected/cya-conferences-studio-remote-grid.webp",
    width: 742,
    height: 557,
    alt: "A grid of colleagues joining a wellbeing session remotely by video call.",
    status: "evidence-required",
    note: "Individual call participants' consent to appear in marketing is not documented. " + PERMISSION_NOTE,
  },
  programsHero: {
    src: "/images/selected/cya-programs-hero-group-class.webp",
    width: 1600,
    height: 1200,
    alt: "A small group moving together during a facilitator-led class.",
    status: "evidence-required",
    note: PERMISSION_NOTE,
  },
  programsContinuity: {
    src: "/images/selected/cya-programs-continuity-group-repeat.webp",
    width: 1600,
    height: 1200,
    alt: "Participants stretching together mid-class.",
    status: "evidence-required",
    note: PERMISSION_NOTE,
  },
  programsMultiSite: {
    src: "/images/selected/cya-programs-multisite-outdoor.webp",
    width: 746,
    height: 560,
    alt: "A group in high-visibility workwear stretching together outdoors.",
    status: "evidence-required",
    note: PERMISSION_NOTE,
  },
  studioEmployeeHome: {
    src: "/images/selected/cya-studio-employee-home-practice.webp",
    width: 1440,
    height: 1080,
    alt: "A person doing a quiet stretch practice at home.",
    status: "evidence-required",
    note: PERMISSION_NOTE,
  },
  aboutHero: {
    src: "/images/selected/cya-about-debby-lewis-portrait.webp",
    width: 1600,
    height: 1200,
    alt: "Debby Lewis, founder of Corporate Yoga Australia.",
    status: "approved",
    note: "Named subject — Debby Lewis, CYA founder. Approved for CYA's own site use.",
  },
  aboutWorldview: {
    src: "/images/selected/cya-about-worldview-group-rest.webp",
    width: 960,
    height: 720,
    alt: "A group resting together on mats during a guided session.",
    status: "evidence-required",
    note: PERMISSION_NOTE,
  },
  aboutFacilitator: {
    src: "/images/selected/cya-about-facilitator-representative.webp",
    width: 1080,
    height: 810,
    alt: "A CYA facilitator, one of the practitioners in the national network.",
    status: "evidence-required",
    note: "Named individual — marketing-use consent not documented; facilitator register and credentials not yet verified. Must be resolved before any production use.",
  },
  aboutDelivery: {
    src: "/images/selected/cya-about-delivery-group-practice.webp",
    width: 1600,
    height: 1200,
    alt: "A facilitator-led group session in progress.",
    status: "evidence-required",
    note: PERMISSION_NOTE,
  },
} satisfies Record<string, MediaAsset>;
