import type { Metadata } from "next";
import Link from "next/link";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { BreadcrumbStructuredData } from "@/components/StructuredData";
import { ProductionAction, ProductionCard, ProductionClosing, ProductionContainer, ProductionKicker } from "@/components/ProductionPrimitives";
import { ReviewImageDirection } from "@/components/ReviewImageDirection";
import { insightArticles } from "@/content/insights";

export const metadata: Metadata = { title: "Workplace Wellbeing Insights", description: "Practical Corporate Yoga Australia insights on workplace wellbeing, Work Wellness, workplace yoga, mindfulness and wellbeing program design.", alternates: { canonical: "/blog" } };
const dateFormatter = new Intl.DateTimeFormat("en-AU", { day: "numeric", month: "short", year: "numeric" });

export default function InsightsPage() {
  const articles = [...insightArticles].sort((a, b) => new Date(b.dateModified).getTime() - new Date(a.dateModified).getTime());
  const [featured, ...rest] = articles;
  return <>
    <BreadcrumbStructuredData items={[{ name: "Insights", path: "/blog" }]} />
    <Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Insights" }]} />
    <section className="bg-[var(--cya-surface-page)] py-16 lg:py-20"><ProductionContainer className="grid gap-10 lg:grid-cols-[1.4fr_0.8fr] lg:items-center"><div><ProductionKicker>Insights</ProductionKicker><h1 className="mt-5 max-w-4xl text-[clamp(2.8rem,5vw,4.5rem)] font-bold leading-[1.05]">Useful workplace wellbeing thinking that connects back to real decisions</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-[var(--cya-body)]">Practical guidance, observations and expert knowledge to help workplace organisers and participants understand, decide or act.</p>{featured && <div className="mt-8 flex gap-3"><ProductionAction href={`/blog/${featured.slug}`}>Read the latest insight</ProductionAction><ProductionAction href="/movement" style="secondary">Explore workplace wellbeing</ProductionAction></div>}</div><aside className="border border-[var(--cya-divider)] bg-[var(--cya-surface-subtle)] p-8"><ProductionKicker>Each Insight helps you</ProductionKicker><ul className="mt-6 space-y-4"><li>Understand a workplace question</li><li>Make a practical decision</li><li>Find a relevant next step</li></ul></aside></ProductionContainer></section>
    <section className="border-y border-[var(--cya-divider)] bg-white py-10"><ProductionContainer className="grid gap-6 md:grid-cols-[1fr_auto] md:items-center"><div><ProductionKicker>CYA concept guide</ProductionKicker><h2 className="mt-3 text-2xl font-bold">What is Work Wellness?</h2><p className="mt-3 max-w-3xl leading-7 text-[var(--cya-body)]">How CYA uses Work Wellness to describe useful wellbeing that becomes part of working life — and why it does not replace the broader category of workplace wellbeing.</p></div><ProductionAction href="/blog/what-is-work-wellness" style="secondary">Read the guide</ProductionAction></ProductionContainer></section>
    <ReviewImageDirection id="IMAGE 10 · INSIGHTS EDITORIAL LEAD" job="Context" subject="A genuine workplace or Corporate Yoga Australia field-note image directly related to the featured Insight, with a clear and factual editorial connection." treatment="One restrained 3:2 lead image. Individual guides may use distinct relevant images later; the index should not become a generic card gallery." format="3:2 desktop · adaptable to 4:3 mobile" avoid="Generic wellness stock, an unrelated group class, repeated imagery from service pages or photographs used only to decorate the index." candidate="/images/selected/cya-insights-field-note.webp" />
    <section className="bg-white py-20 lg:py-24"><ProductionContainer><ProductionKicker>Start with the decision in front of you</ProductionKicker><h2 className="mt-5 text-4xl font-bold lg:text-5xl">Start with one useful guide</h2>{featured && <article className="mt-10 grid gap-8 border-y border-[var(--cya-divider)] py-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-xs font-semibold uppercase text-[var(--cya-ochre-ink)]">{featured.category}</p><h3 className="mt-3 text-3xl"><Link href={`/blog/${featured.slug}`}>{featured.title}</Link></h3><p className="mt-4 max-w-3xl text-[var(--cya-body)]">{featured.summary}</p><p className="mt-4 text-sm text-[var(--cya-body)]">{featured.author} · <time dateTime={featured.datePublished}>{dateFormatter.format(new Date(featured.datePublished))}</time></p></div><ProductionAction href={`/blog/${featured.slug}`} style="secondary">Read insight</ProductionAction></article>}<div className="mt-10 grid gap-5 md:grid-cols-3"><ProductionCard title="Field Notes" body="Observations from real workplace delivery, published with appropriate context." /><ProductionCard title="Expert conversations" body="Credible voices exploring practical wellbeing questions." /><ProductionCard title="Practical guidance" body="Useful explanations connected to workplace decisions and relevant services." /></div>{rest.length > 0 && <div className="mt-12 divide-y divide-[var(--cya-divider)] border-y border-[var(--cya-divider)]">{rest.map(article => <article key={article.slug} className="grid gap-4 py-6 md:grid-cols-[1fr_auto] md:items-center"><div><p className="text-xs font-semibold uppercase text-[var(--cya-ochre-ink)]">{article.category}</p><h3 className="mt-2 text-xl"><Link href={`/blog/${article.slug}`}>{article.title}</Link></h3><p className="mt-2 text-sm text-[var(--cya-body)]">{article.summary}</p></div><Link className="font-semibold underline underline-offset-4" href={`/blog/${article.slug}`}>Read insight</Link></article>)}</div>}</ProductionContainer></section>
    <section className="bg-[var(--cya-surface-page)] py-20 lg:py-24"><ProductionContainer><ProductionKicker>Useful and responsible guidance</ProductionKicker><h2 className="mt-5 text-4xl font-bold lg:text-5xl">Clear context makes advice more useful</h2><div className="mt-10 grid gap-5 md:grid-cols-3"><ProductionCard title="Who it is for" body="Each guide makes its workplace audience and purpose clear." tone="paper" /><ProductionCard title="When it was reviewed" body="Published and updated dates help readers understand how current the guidance is." tone="paper" /><ProductionCard title="Where to go next" body="Relevant service and planning links make the next useful step easy to find." tone="paper" /></div></ProductionContainer></section>
    <ProductionClosing heading="Turn useful thinking into a useful next step" body="Continue into the related service, evidence or planning pathway." href={featured ? `/blog/${featured.slug}` : "/blog"} action="Read the latest insight" />
  </>;
}
