import type { Metadata } from "next";
import Link from "next/link";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { BreadcrumbStructuredData } from "@/components/StructuredData";
import { ProductionAction, ProductionCard, ProductionClosing, ProductionContainer, ProductionKicker, ProductionPhoto } from "@/components/ProductionPrimitives";
import { insightArticles } from "@/content/insights";
import { media } from "@/content/media";

export const metadata: Metadata = { title: "Workplace Wellbeing Insights", description: "Practical Corporate Yoga Australia insights on workplace Yoga, mindfulness and workplace wellbeing program design.", alternates: { canonical: "/blog" } };
const dateFormatter = new Intl.DateTimeFormat("en-AU", { day: "numeric", month: "short", year: "numeric" });

export default function InsightsPage() {
  const articles = [...insightArticles].sort((a, b) => new Date(b.dateModified).getTime() - new Date(a.dateModified).getTime());
  const [featured, ...rest] = articles;
  return <>
    <BreadcrumbStructuredData items={[{ name: "Insights", path: "/blog" }]} />
    <Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Insights" }]} />
    <section className="bg-[var(--cya-paper)] py-16 lg:py-20"><ProductionContainer className="grid gap-10 lg:grid-cols-[1.4fr_0.8fr] lg:items-center"><div><ProductionKicker>Field Notes · expert conversations · guidance</ProductionKicker><h1 className="mt-5 max-w-4xl text-[clamp(2.8rem,5vw,4.5rem)] font-bold leading-[1.05]">Useful thinking for wellbeing in real working life.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-[var(--cya-body)]">An editorial destination for questions, observations and expert knowledge—with clear pathways back to relevant services.</p>{featured && <div className="mt-8 flex gap-3"><ProductionAction href={`/blog/${featured.slug}`}>Read the latest insight</ProductionAction><ProductionAction href="/movement" style="secondary">Explore by need</ProductionAction></div>}</div><aside className="bg-[var(--cya-teal-dark)] p-8 text-white"><ProductionKicker light>Editorial standard</ProductionKicker><ul className="mt-6 space-y-4"><li>Featured insight</li><li>Author and review date</li><li>Related service pathway</li></ul></aside></ProductionContainer></section>
    <ProductionPhoto asset={media.proofHero} label="CYA photography · field note" priority />
    <section className="bg-white py-20 lg:py-24"><ProductionContainer><ProductionKicker>Editorial entry</ProductionKicker><h2 className="mt-5 text-4xl font-bold lg:text-5xl">One strong editorial lead—not a wall of cards.</h2>{featured && <article className="mt-10 grid gap-8 border-y border-[var(--cya-divider)] py-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-xs font-semibold uppercase text-[var(--cya-ochre-ink)]">{featured.category}</p><h3 className="mt-3 text-3xl"><Link href={`/blog/${featured.slug}`}>{featured.title}</Link></h3><p className="mt-4 max-w-3xl text-[var(--cya-body)]">{featured.summary}</p><p className="mt-4 text-sm text-[var(--cya-body)]">{featured.author} · <time dateTime={featured.datePublished}>{dateFormatter.format(new Date(featured.datePublished))}</time></p></div><ProductionAction href={`/blog/${featured.slug}`} style="secondary">Read insight</ProductionAction></article>}<div className="mt-10 grid gap-5 md:grid-cols-3"><ProductionCard title="Field Notes" body="Observations from real workplace delivery, with permission and context." /><ProductionCard title="Expert conversations" body="Credible voices exploring practical wellbeing questions." /><ProductionCard title="Practical guidance" body="Useful explanations connected to workplace decisions and canonical services." /></div>{rest.length > 0 && <div className="mt-12 divide-y divide-[var(--cya-divider)] border-y border-[var(--cya-divider)]">{rest.map(article => <article key={article.slug} className="grid gap-4 py-6 md:grid-cols-[1fr_auto] md:items-center"><div><p className="text-xs font-semibold uppercase text-[var(--cya-ochre-ink)]">{article.category}</p><h3 className="mt-2 text-xl"><Link href={`/blog/${article.slug}`}>{article.title}</Link></h3><p className="mt-2 text-sm text-[var(--cya-body)]">{article.summary}</p></div><Link className="font-semibold underline underline-offset-4" href={`/blog/${article.slug}`}>Read insight</Link></article>)}</div>}</ProductionContainer></section>
    <section className="bg-[var(--cya-canvas)] py-20 lg:py-24"><ProductionContainer><ProductionKicker>Authority rules</ProductionKicker><h2 className="mt-5 text-4xl font-bold lg:text-5xl">Editorial authority supports commercial authority.</h2><div className="mt-10 grid gap-5 md:grid-cols-3"><ProductionCard title="Attribution" body="Author, expertise and reviewed sources are visible." tone="paper" /><ProductionCard title="Freshness" body="Published and updated dates support maintenance and trust." tone="paper" /><ProductionCard title="Relationship" body="Each article links to the most relevant service, evidence or contact pathway." tone="paper" /></div></ProductionContainer></section>
    <ProductionClosing tone="teal" heading="Turn useful thinking into a useful next step." body="Continue into the related service, evidence or planning pathway." href={featured ? `/blog/${featured.slug}` : "/blog"} action="Read the latest insight" />
  </>;
}
