import type { Metadata } from "next";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { BreadcrumbStructuredData, FounderStructuredData } from "@/components/StructuredData";
import { ProductionAction, ProductionCard, ProductionClosing, ProductionContainer, ProductionKicker } from "@/components/ProductionPrimitives";
import { ReviewImageDirection } from "@/components/ReviewImageDirection";

export const metadata: Metadata = { title: "About Corporate Yoga Australia", description: "Corporate Yoga Australia grew from Debby Lewis's own workplace-wellbeing practice into a national business, founded in 2014.", alternates: { canonical: "/about-us" } };

export default function AboutUsPage() {
  return <>
    <BreadcrumbStructuredData items={[{ name: "About", path: "/about-us" }]} /><FounderStructuredData />
    <Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "About" }]} />
    <section className="bg-[var(--cya-surface-page)] py-16 lg:py-20"><ProductionContainer className="grid gap-10 lg:grid-cols-[1.4fr_0.8fr] lg:items-center"><div><ProductionKicker>Human permission · organisational confidence</ProductionKicker><h1 className="mt-5 max-w-4xl text-[clamp(2.8rem,5vw,4.5rem)] font-bold leading-[1.05]">A human service built for the realities of work.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-[var(--cya-body)]">CYA combines thoughtful curation, experienced facilitators and practical coordination. The relationship—not a catalogue—is the centre of the offer.</p><div className="mt-8 flex gap-3"><ProductionAction href="#relationship">Meet CYA</ProductionAction><ProductionAction href="/contact" style="secondary">Start planning</ProductionAction></div></div><aside className="border border-[var(--cya-divider)] bg-white p-8"><ProductionKicker>Trust depends on</ProductionKicker><ul className="mt-6 space-y-4"><li>Founder story</li><li>Facilitator fit</li><li>Client relationship</li></ul></aside></ProductionContainer></section>
    <ReviewImageDirection id="IMAGE 09 · DEBBY AND THE CYA RELATIONSHIP" job="Human trust" subject="A current, approved image of Debby Lewis in a natural CYA planning or facilitation context, supported later by one genuine delivery image." treatment="Warm, light-led portrait or environmental image. Keep it credible and service-focused rather than lifestyle-led." format="4:3 or 3:2 desktop · adaptable to portrait mobile crop" avoid="Generic founder portraiture, over-styled personal branding, unrelated yoga poses or an image that hides the workplace relationship." candidate="/images/selected/cya-about-planning.webp" />
    <section className="bg-white py-20 lg:py-24"><ProductionContainer><ProductionKicker>Our beginnings</ProductionKicker><h2 className="mt-5 max-w-4xl text-4xl font-bold lg:text-5xl">Built from experience inside the workplace.</h2><p className="mt-5 max-w-4xl text-lg leading-8 text-[var(--cya-body)]">While working in a high-pressure HR role, Debby Lewis experienced how difficult it can be to protect your wellbeing during a demanding working day. Movement and meditation became practical ways for her to manage that pressure. In 2014, she founded Corporate Yoga Australia to make the same kind of support easier for people to access at work.</p></ProductionContainer></section>
    <section id="relationship" className="bg-[var(--cya-surface-subtle)] py-20 lg:py-24"><ProductionContainer><ProductionKicker>Relationship</ProductionKicker><h2 className="mt-5 text-4xl font-bold lg:text-5xl">Why organisations stay with CYA.</h2><p className="mt-5 max-w-4xl text-lg text-[var(--cya-body)]">Organisations return because CYA understands the context, coordinates the practical details and adapts when people, schedules or workplace needs change.</p><div className="mt-10 grid gap-5 md:grid-cols-3"><ProductionCard title="Human curation" body="The right facilitator and format are selected for the specific context." /><ProductionCard title="Responsive service" body="CYA adapts when rooms, schedules, participation or organisational needs change." /><ProductionCard title="Organisational confidence" body="Clear communication, coordination, boundaries and evidence support approval." /></div></ProductionContainer></section>
    <section className="bg-[var(--cya-surface-page)] py-20 lg:py-24"><ProductionContainer><ProductionKicker>Standards</ProductionKicker><h2 className="mt-5 text-4xl font-bold lg:text-5xl">Facilitator fit is fundamental to the experience.</h2><p className="mt-5 max-w-4xl text-lg text-[var(--cya-body)]">Trust depends on the people delivering the experience and their ability to work safely and responsively within each context.</p><div className="mt-10 grid gap-5 md:grid-cols-3"><ProductionCard title="Capability" body="Relevant qualifications, experience and clear service boundaries." tone="paper" /><ProductionCard title="Presence" body="Warm, inclusive facilitation without pressure or performance." tone="paper" /><ProductionCard title="Context" body="The ability to adapt safely to different people, places and workplace moments." tone="paper" /></div></ProductionContainer></section>
    <ProductionClosing heading="Plan with people who understand working context." body="Tell CYA what the organisation needs and how people will experience it." />
  </>;
}
