import type { Metadata } from "next";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { ServiceStructuredData } from "@/components/StructuredData";
import { ProductionAction, ProductionCard, ProductionClosing, ProductionContainer, ProductionKicker } from "@/components/ProductionPrimitives";
import { ReviewImageDirection } from "@/components/ReviewImageDirection";

export const metadata: Metadata = { title: { absolute: "Workplace Wellbeing Workshops Australia | CYA" }, description: "Expert-led workplace wellbeing workshops and Lunch & Learns for Australian teams.", alternates: { canonical: "/workplace-wellbeing-workshops" } };

export default function WorkplaceWellbeingWorkshopsPage() {
  return <>
    <ServiceStructuredData name="Workplace Wellbeing Workshops & Expert Experiences" description="Expert-led workplace wellbeing workshops and Lunch & Learns for Australian teams." path="/workplace-wellbeing-workshops" breadcrumbLabel="Workplace Wellbeing Workshops" />
    <Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Workplace Wellbeing Workshops" }]} />
    <section className="bg-[var(--cya-paper)] py-16 lg:py-20"><ProductionContainer className="grid gap-10 lg:grid-cols-[1.4fr_0.8fr] lg:items-center"><div><ProductionKicker>Workshops · talks · facilitated experiences</ProductionKicker><h1 className="mt-5 max-w-4xl text-[clamp(2.8rem,5vw,4.5rem)] font-bold leading-[1.05]">Expert-led experiences that create useful workplace conversation.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-[var(--cya-body)]">Credible people, relevant topics and formats shaped around the organisation—not a generic speaker catalogue.</p><div className="mt-8 flex gap-3"><ProductionAction href="/contact?interest=workshop">Plan an expert experience</ProductionAction><ProductionAction href="#topics" style="secondary">Explore topics</ProductionAction></div></div><aside className="bg-[var(--cya-teal-dark)] p-8 text-white"><ProductionKicker light>What makes it credible</ProductionKicker><ul className="mt-6 space-y-4"><li>Topic relevance</li><li>Expert authority</li><li>Participation design</li></ul></aside></ProductionContainer></section>
    <ReviewImageDirection id="IMAGE 06 · WORKSHOP OR EXPERT EXPERIENCE" job="Human trust" subject="A real CYA workshop, Lunch & Learn or expert-led workplace conversation with the facilitator and audience interaction both visible." treatment="Contained 3:2 editorial image with natural attention and participation rather than a staged presentation pose." format="3:2 desktop · adaptable to 4:3 mobile" avoid="Generic conference stock, a distant speaker on a stage, unreadable projected screens or an image unrelated to the confirmed topic." candidate="/images/selected/cya-conferences-events-hero.webp" />
    <section id="topics" className="bg-white py-20 lg:py-24"><ProductionContainer><ProductionKicker>Topic-led discovery</ProductionKicker><h2 className="mt-5 text-4xl font-bold lg:text-5xl">Begin with the conversation the workplace needs.</h2><p className="mt-5 max-w-4xl text-lg text-[var(--cya-body)]">Expert Experiences are selected by relevance, credibility and participation design—not speaker celebrity alone.</p><div className="mt-10 grid gap-5 md:grid-cols-3"><ProductionCard title="Mental fitness and sustainable performance" body="Practical ways to think about attention, pressure, recovery and working rhythm." /><ProductionCard title="Communication and connection" body="Useful conversations about trust, listening, boundaries and team relationships." /><ProductionCard title="Sleep, energy and everyday wellbeing" body="Credible expertise translated into actions people can use beyond the session." /></div></ProductionContainer></section>
    <section className="bg-[var(--cya-canvas)] py-20 lg:py-24"><ProductionContainer><ProductionKicker>What makes the experience credible</ProductionKicker><h2 className="mt-5 text-4xl font-bold lg:text-5xl">Relevant expertise, thoughtful facilitation and a useful next step.</h2><div className="mt-10 grid gap-5 md:grid-cols-3"><ProductionCard title="Expert authority" body="Relevant professional knowledge and clear boundaries." tone="paper" /><ProductionCard title="Facilitation" body="A format designed for participation, not a one-way lecture." tone="paper" /><ProductionCard title="Continuation" body="Insights or Online Wellbeing resources can extend the useful moment." tone="paper" /></div></ProductionContainer></section>
    <ProductionClosing tone="teal" heading="Bring the right expertise into the room." body="Start with the topic, audience and conversation the organisation needs." href="/contact?interest=workshop" action="Plan an expert experience" />
  </>;
}
