import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { ServiceStructuredData } from "@/components/StructuredData";
import { ProductionAction, ProductionContainer, ProductionKicker } from "@/components/ProductionPrimitives";

export const metadata: Metadata = {
  title: { absolute: "Workplace Wellbeing Programs Australia | Corporate Yoga Australia" },
  description: "Tailored workplace wellbeing programs combining movement, mindfulness, workshops, expert experiences and ongoing support for Australian organisations.",
  alternates: { canonical: "/workplace-wellbeing-programs" },
};

const programSteps = [
  ["01", "Understand the workplace", "People, locations, schedules, working patterns and what needs to happen."],
  ["02", "Shape the right mix", "Choose useful experiences around the people, context and goals rather than a fixed package."],
  ["03", "Create a useful rhythm", "Build a cadence people can realistically participate in and return to across the working week."],
  ["04", "Learn and evolve", "Use aggregate participation, delivery experience and voluntary feedback to refine what continues."],
] as const;

const ingredients = [
  { number: "01", title: "Movement", body: "Yoga, Pilates, mobility and accessible movement for different workplace settings.", href: "/movement" },
  { number: "02", title: "Mindfulness and reset", body: "Meditation, breathing and short practices that help people pause, reset and return.", href: "/meditation-mindfulness" },
  { number: "03", title: "Workshops & expert experiences", body: "Useful conversations, learning and facilitated experiences shaped around a workplace need.", href: "/workplace-wellbeing-workshops" },
  { number: "04", title: "Ongoing support", body: "Regular live experiences with Wellbeing Studio support between scheduled moments.", href: "/online-wellbeing" },
] as const;

const workplaceRhythms = [
  ["Office and professional environments", "Fit around meetings, shared spaces and desk-based working patterns."],
  ["Operational and industrial workplaces", "Adapt to shifts, environments, clothing, access and the space available."],
  ["Multi-site and distributed teams", "Coordinate a shared program while allowing delivery to work differently in each location."],
  ["Hybrid workforces", "Combine live and digital support without assuming everyone works in the same place or way."],
] as const;

const faqs = [
  ["Can we start small before committing to an ongoing program?", "Yes. A one-off experience, focused pilot or short series can be a useful way to learn what fits before deciding whether greater continuity would help."],
  ["What can a workplace wellbeing program include?", "A program can combine workplace yoga, Pilates, mindfulness, workshops, specialist sessions, campaigns, live online experiences and Wellbeing Studio support. The mix is shaped around your people, locations, schedules and goals rather than a fixed package."],
  ["Can programs support different locations, workforces and hybrid teams?", "Yes. We confirm the people, locations, access needs, available spaces and working patterns before recommending a mix of onsite delivery, live online sessions and ongoing digital support."],
  ["How do you decide how often sessions should run?", "Cadence depends on what the program is trying to support, the time people can realistically use and the working patterns of the organisation. A focused pilot, short series or regular rhythm can all be appropriate starting points."],
  ["How are facilitators and formats selected?", "Facilitators and formats are matched to the experience, participant group, workplace setting and program goals. The aim is to make delivery appropriate to the people and context rather than use one standard format everywhere."],
  ["How is participation reviewed?", "We use proportionate, privacy-aware measures such as aggregate participation, delivery experience and voluntary feedback. Individual wellbeing is not monitored or assessed."],
] as const;

export default function WorkplaceWellbeingProgramsPage() {
  return (
    <>
      <ServiceStructuredData name="Workplace Wellbeing Programs" description="Tailored workplace wellbeing programs combining human-led experiences, practical coordination and ongoing support for Australian teams." path="/workplace-wellbeing-programs" breadcrumbLabel="Workplace wellbeing programs" />
      <Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Workplace wellbeing programs" }]} />

      <section className="bg-[var(--cya-surface-page)] py-12 sm:py-14 lg:py-16">
        <ProductionContainer className="grid max-w-[1440px] gap-10 lg:grid-cols-[minmax(0,1.05fr)_minmax(0,0.95fr)] lg:items-center lg:gap-14 xl:gap-16">
          <div><ProductionKicker>Workplace wellbeing programs</ProductionKicker><h1 className="mt-5 max-w-3xl text-[clamp(3rem,4.8vw,4.55rem)] font-bold leading-[1.03] tracking-[-0.025em] text-[var(--cya-teal-dark)]">Workplace wellbeing built around how your organisation works</h1><p className="mt-7 max-w-2xl text-xl leading-8 text-[var(--cya-body)]">Bring movement, mindfulness, workshops and ongoing support together in a program shaped around your people, locations and working day.</p><div className="mt-9"><ProductionAction href="/contact?interest=program">Tell us what you’re planning</ProductionAction></div></div>
          <figure className="relative aspect-[4/3] overflow-hidden bg-white"><Image src="/images/selected/cya-workplace-wellbeing-hero-warehouse-group.webp" alt="Employees take part in a facilitated workplace wellbeing session in an operational workplace." fill priority sizes="(min-width: 1280px) 620px, (min-width: 1024px) 48vw, 100vw" className="object-cover" /></figure>
        </ProductionContainer>
        <ProductionContainer className="mt-10"><div className="grid border-t border-[var(--cya-ochre)] pt-6 md:grid-cols-2 md:items-center"><h2 className="text-2xl font-semibold tracking-[-0.015em] text-[var(--cya-teal-dark)]">Wellbeing belongs in the workday</h2><p className="mt-3 text-base text-[var(--cya-teal-dark)] md:mt-0 md:text-right">Practical, inclusive and shaped around working life.</p></div></ProductionContainer>
      </section>

      <section className="bg-white py-20 lg:py-24"><ProductionContainer className="grid gap-12 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)] lg:items-center lg:gap-16"><figure className="relative aspect-[4/3] overflow-hidden bg-[var(--cya-surface-page)]"><Image src="/images/selected/cya-workplace-wellbeing-lunch-learn-team.webp" alt="A workplace group takes part in an accessible facilitated wellbeing experience." fill sizes="(min-width: 1280px) 620px, (min-width: 1024px) 50vw, 100vw" className="object-cover" /></figure><div><ProductionKicker>Begin with the outcome</ProductionKicker><h2 className="mt-5 max-w-2xl text-4xl font-bold tracking-[-0.018em] text-[var(--cya-teal-dark)] lg:text-5xl">A program can start with one clear need</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-[var(--cya-body)]">A regular movement class. A wellbeing campaign. Support for a distributed team. We shape the delivery around what would help your people now — and what can be sustained.</p><div className="mt-8"><ProductionAction href="/contact?interest=program" style="secondary">Discuss your workplace</ProductionAction></div></div></ProductionContainer></section>

      <section className="bg-[var(--cya-surface-page)] py-20 lg:py-24"><ProductionContainer><ProductionKicker>Build the right mix</ProductionKicker><h2 className="mt-5 max-w-4xl text-4xl font-bold tracking-[-0.018em] text-[var(--cya-teal-dark)] lg:text-5xl">Combine what helps, without turning wellbeing into a package</h2><p className="mt-5 max-w-3xl text-lg leading-8 text-[var(--cya-body)]">Choose a useful starting point, then connect experiences where greater continuity makes sense.</p><div className="mt-10 flex snap-x snap-mandatory gap-5 overflow-x-auto pb-4 md:grid md:grid-cols-4 md:overflow-visible md:pb-0">{ingredients.map((item) => <article key={item.number} className="min-w-[84%] snap-start border-y border-[var(--cya-divider)] bg-white px-1 py-7 sm:min-w-[60%] md:min-w-0 md:px-5"><p className="text-xs font-semibold text-[var(--cya-ochre-ink)]">{item.number}</p><h3 className="mt-4 text-xl font-semibold leading-7 text-[var(--cya-teal-dark)]">{item.title}</h3><p className="mt-3 leading-7 text-[var(--cya-body)]">{item.body}</p><Link href={item.href} className="mt-5 inline-flex font-semibold text-[var(--cya-teal-dark)] hover:underline">Explore →</Link></article>)}</div><p className="mt-2 text-sm text-[var(--cya-body)] md:hidden">Swipe to explore →</p></ProductionContainer></section>

      <section id="program-shape" className="bg-white py-20 lg:py-24"><ProductionContainer className="grid gap-12 lg:grid-cols-[minmax(18rem,0.72fr)_minmax(0,1.28fr)] lg:gap-20"><div><ProductionKicker>How a program takes shape</ProductionKicker><h2 className="mt-5 max-w-xl text-4xl font-bold tracking-[-0.018em] text-[var(--cya-teal-dark)] lg:text-5xl">Start with the workplace, then build a rhythm around it</h2><p className="mt-6 max-w-xl text-lg leading-8 text-[var(--cya-body)]">The program is shaped around how work happens, not assembled from a fixed set of inclusions.</p></div><div className="flex snap-x snap-mandatory gap-4 overflow-x-auto pb-4 md:block md:overflow-visible md:pb-0">{programSteps.map(([number,title,body]) => <article key={number} className="min-w-[80%] snap-start border-y border-[var(--cya-divider)] px-2 py-6 sm:min-w-[60%] md:grid md:min-w-0 md:grid-cols-[3rem_0.75fr_1.25fr] md:gap-5 md:border-t-0 md:border-b md:px-0 md:first:border-t"><p className="text-xs font-semibold text-[var(--cya-ochre-ink)]">{number}</p><h3 className="mt-3 text-xl font-semibold leading-7 text-[var(--cya-charcoal)] md:mt-0">{title}</h3><p className="mt-3 leading-7 text-[var(--cya-body)] md:mt-0">{body}</p></article>)}</div><p className="text-sm text-[var(--cya-body)] md:hidden lg:col-start-2">Swipe to continue →</p></ProductionContainer></section>

      <section className="bg-[var(--cya-surface-page)] py-16 lg:py-20"><ProductionContainer className="grid gap-10 lg:grid-cols-[minmax(0,1.08fr)_minmax(0,0.92fr)] lg:items-stretch lg:gap-12 xl:gap-14"><figure className="relative min-h-[34rem] overflow-hidden bg-white lg:min-h-[40rem]"><Image src="/images/selected/cya-programs-continuity-group-repeat.webp" alt="Participants stretch together during a facilitator-led workplace wellbeing session." fill sizes="(min-width: 1280px) 700px, (min-width: 1024px) 52vw, 100vw" className="object-cover" /></figure><div className="flex flex-col justify-center lg:pl-2"><ProductionKicker>Designed for participation</ProductionKicker><h2 className="mt-5 max-w-2xl text-4xl font-bold tracking-[-0.018em] text-[var(--cya-teal-dark)] lg:text-[2.75rem] xl:text-5xl">A useful program has to work for the people using it</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-[var(--cya-body)]">Timing, location, access, communication and choice all affect whether people can realistically take part.</p><div className="mt-8 border-y border-[var(--cya-divider)]"><article className="border-b border-[var(--cya-divider)] py-5"><h3 className="text-[1.35rem] font-semibold leading-7 text-[var(--cya-teal-dark)]">Fits the working day</h3><p className="mt-2 text-[1.05rem] leading-7 text-[var(--cya-body)]">Times, formats and locations that reflect how people actually work.</p></article><article className="border-b border-[var(--cya-divider)] py-5"><h3 className="text-[1.35rem] font-semibold leading-7 text-[var(--cya-teal-dark)]">Clear to participants</h3><p className="mt-2 text-[1.05rem] leading-7 text-[var(--cya-body)]">People know what the experience involves and how to join.</p></article><article className="py-5"><h3 className="text-[1.35rem] font-semibold leading-7 text-[var(--cya-teal-dark)]">Voluntary and privacy-aware</h3><p className="mt-2 text-[1.05rem] leading-7 text-[var(--cya-body)]">Participation and feedback without assessing individual wellbeing.</p></article></div></div></ProductionContainer></section>

      <section className="bg-white py-20 lg:py-24"><ProductionContainer><div className="grid gap-10 lg:grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)] lg:items-end lg:gap-16"><div className="max-w-2xl"><ProductionKicker>Different workplaces, different rhythms</ProductionKicker><h2 className="mt-5 text-4xl font-bold tracking-[-0.018em] text-[var(--cya-teal-dark)] lg:text-5xl">The program changes with the workplace</h2><p className="mt-6 text-lg leading-8 text-[var(--cya-body)]">The same wellbeing idea can need a different delivery approach depending on the environment, workforce and way the day is structured.</p></div><figure className="relative aspect-[16/9] overflow-hidden bg-[var(--cya-surface-page)]"><Image src="/images/cya-library/IMG_5701.JPG" alt="Employees in high-visibility workwear take part in an outdoor workplace wellbeing session." fill sizes="(min-width: 1280px) 760px, (min-width: 1024px) 58vw, 100vw" className="object-cover" /></figure></div><div className="mt-10 grid border-y border-[var(--cya-divider)] md:grid-cols-2 lg:grid-cols-4">{workplaceRhythms.map(([title,body],index) => <article key={title} className="border-b border-[var(--cya-divider)] px-0 py-6 md:px-6 lg:border-b-0 lg:border-l lg:first:border-l-0 lg:first:pl-0 lg:last:pr-0"><p className="text-xs font-semibold text-[var(--cya-ochre-ink)]">{String(index+1).padStart(2,"0")}</p><h3 className="mt-3 text-lg font-semibold leading-6 text-[var(--cya-teal-dark)]">{title}</h3><p className="mt-2 leading-6 text-[var(--cya-body)]">{body}</p></article>)}</div></ProductionContainer></section>

      <section className="overflow-hidden bg-[var(--cya-surface-base)] py-20 lg:py-24"><ProductionContainer><div className="grid gap-10 lg:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)] lg:items-end lg:gap-16"><div className="pb-2"><ProductionKicker>Connected support</ProductionKicker><h2 className="mt-5 max-w-2xl text-4xl font-bold tracking-[-0.018em] text-[var(--cya-teal-dark)] lg:text-5xl">Support people can return to between live experiences</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-[var(--cya-body)]">For ongoing programs, Wellbeing Studio gives participants practical ways to return to wellbeing between scheduled experiences. It extends the human-led program rather than replacing it.</p><div className="mt-8"><ProductionAction href="/online-wellbeing">Explore online wellbeing</ProductionAction></div></div><div><p className="mb-4 text-xs font-bold uppercase tracking-[0.14em] text-[var(--cya-ochre-ink)]">Live experience → return → continuity</p><figure className="relative aspect-[2048/970] overflow-hidden border border-[var(--cya-divider)] bg-white shadow-[0_18px_50px_rgba(14,67,74,0.08)]"><Image src="/images/selected/wellbeing-studio-placeholder.png" alt="Wellbeing Studio interface showing practical wellbeing support for different moments in the working day." fill sizes="(min-width: 1024px) 62vw, 100vw" className="object-contain" /></figure></div></div></ProductionContainer></section>

      <section className="bg-white py-20 lg:py-24"><ProductionContainer><div className="max-w-4xl"><ProductionKicker>Program experience in practice</ProductionKicker><h2 className="mt-5 text-4xl font-bold tracking-[-0.018em] text-[var(--cya-teal-dark)] lg:text-5xl">One relationship. Different needs over time</h2><p className="mt-6 text-lg leading-8 text-[var(--cya-body)]">Our work with Cromwell Property Group shows how an ongoing program can connect different experiences, locations and periods of support without relying on one fixed format.</p></div><div className="mt-12 grid gap-10 lg:grid-cols-[minmax(0,1.1fr)_minmax(22rem,0.9fr)] lg:items-stretch lg:gap-12"><figure className="relative min-h-[28rem] overflow-hidden bg-[var(--cya-surface-page)]"><Image src="/images/selected/cya-workplace-wellbeing-lunch-learn-team.webp" alt="Employees take part in a facilitated workplace wellbeing experience." fill sizes="(min-width: 1280px) 720px, (min-width: 1024px) 58vw, 100vw" className="object-cover" /></figure><div className="bg-[var(--cya-surface-warm)] px-7 py-8 sm:px-9 lg:px-10 lg:py-10"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[var(--cya-ochre-ink)]">Cromwell Property Group</p><div className="mt-6 border-y border-[var(--cya-mid-neutral)]/50">{["Recurring workplace yoga and Pilates","10- and 20-week programs","Workplace activations and Lunch & Learns","Digital wellbeing support","Delivery across Queensland, New South Wales and Victoria"].map((item,index) => <div key={item} className="grid grid-cols-[2.5rem_1fr] gap-3 border-b border-[var(--cya-mid-neutral)]/50 py-4 last:border-b-0"><span className="text-xs font-semibold text-[var(--cya-ochre-ink)]">{String(index+1).padStart(2,"0")}</span><p className="font-semibold leading-6 text-[var(--cya-teal-dark)]">{item}</p></div>)}</div><div className="mt-7"><ProductionAction href="/case-studies" style="secondary">View case studies</ProductionAction></div></div></div></ProductionContainer></section>

      <section className="bg-[var(--cya-surface-base)] py-16 lg:py-20"><ProductionContainer><ProductionKicker>Clear delivery and review</ProductionKicker><div className="mt-5 grid gap-8 lg:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)] lg:items-end"><div><h2 className="max-w-3xl text-4xl font-bold tracking-[-0.018em] text-[var(--cya-teal-dark)] lg:text-[2.75rem]">Enough structure to make the program easy to run</h2><p className="mt-5 max-w-3xl text-lg leading-8 text-[var(--cya-body)]">We agree the practical details before launch, keep participation clear and use proportionate review to understand what should continue or change.</p></div><div className="grid border-y border-[var(--cya-divider)] sm:grid-cols-2 lg:grid-cols-4">{[["01","Scope","Who, where, what and when."],["02","Participation","Clear information and voluntary access."],["03","Delivery","Appropriate facilitators and formats."],["04","Review","Aggregate participation and useful feedback."]].map(([number,title,body]) => <article key={number} className="border-b border-[var(--cya-divider)] px-5 py-5 last:border-b-0 lg:border-b-0 lg:border-l lg:first:border-l-0"><p className="text-xs font-semibold text-[var(--cya-ochre-ink)]">{number}</p><h3 className="mt-3 text-lg font-semibold text-[var(--cya-teal-dark)]">{title}</h3><p className="mt-1.5 text-sm leading-6 text-[var(--cya-body)]">{body}</p></article>)}</div></div></ProductionContainer></section>

      <section className="bg-white py-20 lg:py-24"><ProductionContainer className="grid gap-10 lg:grid-cols-[minmax(16rem,0.65fr)_minmax(0,1.35fr)] lg:gap-20"><div><ProductionKicker>Practical questions</ProductionKicker><h2 className="mt-5 text-4xl font-bold tracking-[-0.018em] text-[var(--cya-charcoal)] lg:text-5xl">Questions organisations often ask</h2></div><div className="border-t border-[var(--cya-divider)]">{faqs.map(([question,answer]) => <details key={question} className="group border-b border-[var(--cya-divider)] py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 text-lg font-semibold text-[var(--cya-charcoal)]"><span>{question}</span><span aria-hidden="true" className="text-xl transition-transform group-open:rotate-45">+</span></summary><p className="mt-4 max-w-3xl pr-10 leading-7 text-[var(--cya-body)]">{answer}</p></details>)}</div></ProductionContainer></section>

      <section className="border-t border-[var(--cya-ochre)] bg-[var(--cya-surface-page)] py-16 lg:py-20"><ProductionContainer className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-center"><div><h2 className="max-w-3xl text-4xl font-bold tracking-[-0.018em] text-[var(--cya-teal-dark)] lg:text-5xl">What would help your people right now?</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-[var(--cya-teal-dark)]">Tell us what you are planning and we will help you find a useful starting point.</p></div><ProductionAction href="/contact?interest=program">Start a conversation</ProductionAction></ProductionContainer></section>
    </>
  );
}
